export const GENERIC_PLAYER_HOST_PATTERNS = [
  "*://*.cdnvideohub.com/*",
  "*://*.okcdn.ru/*",
  "*://*.kodikplayer.com/*",
  "*://kodikplayer.com/*",
  "*://*.kodik.info/*",
  "*://*.kodik.biz/*",
  "*://*.kodik.cc/*",
  "*://*.wikianimex.ru/*",
  "*://wikianimex.ru/*",
  "*://iframe.mediadelivery.net/*",
  "*://video.bunnycdn.com/*",
  "*://*.cloudflarestream.com/*",
  "*://*.solodcdn.com/*",
  "*://*.vjs.zemcdn.com/*",
] as const;
