export const GENERIC_PLAYER_SELECTORS = [
  ".player",
  ".video-player",
  ".video_player",
  ".video-container",
  ".video-wrapper",
  ".player-container",
  ".player-wrapper",
  ".plyr",
  ".jwplayer",
  ".shaka-video-container",
  ".dplayer",
  ".artplayer",
  ".vjs-player",
  ".video-js",
  "[data-player]",
  "[data-player-container]",
  "[data-video-player]",
  "[data-testid*='player']",
  "[class*='player']",
  "[class*='Player']",
  "[class*='video-player']",
  "[class*='VideoPlayer']",
  "[class*='video-container']",
  "[id*='player']",
  "video-player",
  "video",
] as const;

export const GENERIC_PLAYER_SELECTOR = GENERIC_PLAYER_SELECTORS.join(", ");
